apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: AccenturePoc
  description: The AccenturePoc API
  tags:
    - store
    - rest
  links:
    - url: https://github.com/DoubleDdidi/poc-test-svc
      title: GitHub Repo
      icon: github
    - url: https://github.com/DoubleDdidi/poc-test-svc/blob/master/src/swagger.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: experimental
  owner: user:guest
  dependsOn: accenture-poc-svc
  definition:
    $text: https://github.com/DoubleDdidi/poc-test-svc/blob/master/src/info/swagger.yaml
    