apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "AccenturePoc"
spec:
  tags:
    - spotify
    - rest
  annotations:
    # The annotation is deprecated, we use placeholders (see below) instead, remove it later.
    backstage.io/definition-at-location: 'url:https://raw.githubusercontent.com/APIs-guru/openapi-directory/master/APIs/spotify.com/v1/swagger.yaml'
